### ISSUE TITLE
Code for computing patterns?

### ISSUE THREAD

**Issue by robintibor** [yulongwang12/visual-attribution#1]
Hi,

thanks for sharing this code! 
Could you add some code for computing the patterns for PatternNet etc.? That would be very helpful.

Thanks,
Robin

**Comment by yulongwang12** [comment]
I convert the pattern weights directly from released repo [nn-patterns](https://github.com/pikinder/nn-patterns). And I cannot figure out the exact computation procedure from the original paper. Maybe you can find some clues in this [code snippet](https://github.com/pikinder/nn-patterns/blob/master/nn_patterns/patterns/mixture.py#L190), or you can directly contact the original author for more details.

**Comment by robintibor** [comment]
Ok thanks!
