### ISSUE TITLE
Pattern weights

### ISSUE THREAD

**Issue by t-vi** [yulongwang12/visual-attribution#2]
Hi,

the download URL seems to have gone.
Is there a copy somewhere else?
Thank you!

Best regards

Thomas

**Comment by yulongwang12** [comment]
Hi, I have updated the pattern weights links in [the latest commit](https://github.com/yulongwang12/visual-attribution/commit/7636c272d417ef89298af07864e317ee9de7cd7f). Sorry for the late reply.
